apiVersion: apps/v1
kind: Deployment
metadata:
  name: userserviceblog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userserviceblog
  template:
    metadata:
      labels:
        app: userserviceblog
    spec:
      containers:
        - name: userserviceblog
          image: docker.io/library/userserviceblog-app:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/securityAppBlog"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: userserviceblog
spec:
  selector:
    app: userserviceblog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
